apiVersion: v1
kind: Pod
metadata:
  name: {{ pod_name }}
spec:
  containers:
  - name: db-benchmark
    image: "{{ image }}"
    command:
     - /bin/bash
     - -c
     - |
       set -ex
       mysql --defaults-extra-file=/secret/sql-config.cnf < ./delete-tables.sql
       mysql --defaults-extra-file=/secret/sql-config.cnf < ./create-tables.sql
       python3 benchmark.py
    volumeMounts:
      - mountPath: /secret
        readOnly: true
        name: db-secret
    env:
      - name: N_REPLICATES
        value: "{{ n_replicates }}"
      - name: PARALLELISM
        value: "{{ parallelism }}"
      - name: BATCH_SIZES
        value: "{{ batch_sizes }}"
      - name: CHUNK_SIZE
        value: "{{ chunk_size }}"
  volumes:
    - name: db-secret
      secret:
        secretName: "{{ db_secret_name }}"
  restartPolicy: Never
