kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: batch2
  namespace: {{ batch_pods_ns.name }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: none
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: batch2-storage-class-quota
  namespace: {{ batch_pods_ns.name }}
spec:
  hard:
    batch2.storageclass.storage.k8s.io/requests.storage: 100Ti
    batch2.storageclass.storage.k8s.io/persistentvolumeclaims: 100000
