apiVersion: v1
kind: ServiceAccount
metadata:
  name: batch2
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: batch2
  labels:
    app: batch2
    hail.is/sha: "{{ code.sha }}"
spec:
  selector:
    matchLabels:
      app: batch2
  replicas: 1
  template:
    metadata:
      labels:
        app: batch2
        hail.is/sha: "{{ code.sha }}"
        grafanak8sapp: "true"
    spec:
      serviceAccountName: batch2
{% if deploy %}
      priorityClassName: production
{% endif %}
      containers:
      - name: batch2
        image: "{{ batch2_image.image }}"
        resources:
          requests:
            memory: "1G"
            cpu: "1"
        env:
         - name: HAIL_POD_NAMESPACE
           value: "{{ batch_pods_ns.name }}"
         - name: HAIL_JWT_SECRET_KEY_FILE
           value: /jwt-secret-key/secret-key
         - name: BATCH_IMAGE
           value: "{{ batch2_image.image }}"
         - name: BATCH_NAMESPACE
           value: "{{ default_ns.name }}"
{% if deploy %}
         - name: HAIL_INSTANCE_ID
           value: cd50b95a89914efb897965a5e982a29d
{% endif %}
        ports:
         - containerPort: 5000
        volumeMounts:
         - name: batch2-user-secret
           mountPath: /batch-user-secret
           readOnly: true
         - name: jwt-secret-key
           mountPath: /jwt-secret-key
           readOnly: true
         - name: gsa-key
           mountPath: /batch-gsa-key
           readOnly: true
         - name: batch-jwt
           mountPath: /batch-jwt
           readOnly: true
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
       - name: batch2-user-secret
         secret:
           optional: false
           secretName: "{{ batch2_database.user_secret_name }}"
       - name: jwt-secret-key
         secret:
           optional: false
           secretName: jwt-secret-key
       - name: gsa-key
         secret:
           optional: false
           secretName: batch-gsa-key
       - name: batch-jwt
         secret:
           optional: false
           secretName: batch-jwt
      tolerations:
      - key: "preemptible"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: batch2
  labels:
    app: batch2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: batch2
