apiVersion: v1
kind: Pod
metadata:
  name: test-batch
spec:
  containers:
  - name: test-batch
    image: "{{ test_batch_image.image }}"
    env:
     - name: POD_IP
       valueFrom:
         fieldRef:
           fieldPath: status.podIP
     - name: HAIL_TOKEN_FILE
       value: '/test-jwt/jwt'
     - name: BATCH_URL
       value: http://batch.{{ default_ns.name }}
    volumeMounts:
      - mountPath: /test-jwt
        readOnly: true
        name: test-jwt
  volumes:
    - name: test-jwt
      secret:
        secretName: test-jwt
  restartPolicy: Never
