---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark
  labels:
    app: benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchmark
  template:
    metadata:
      labels:
        app: benchmark
    spec:
      containers:
        - name: benchmark
          image: "{{ benchmark_image.image }}"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: session-secret-key
              mountPath: /session-secret-key
              readOnly: true