FROM konradjk/vep85_loftee:1.0.3

ENV VEP_VERSION 85
ENV VEP_DIR /vep_bin
ENV REFERENCE_GENOME grch37

RUN echo "APT::Acquire::Retries \"5\";" > /etc/apt/apt.conf.d/80-retries && \
    mkdir -p /usr/share/keyrings/ && \
    apt-get update -y && \
    apt-get install -y curl gnupg software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update -y && \
    apt-get install -y python3.5

RUN mv /vep $VEP_DIR

WORKDIR $VEP_DIR/ensembl-tools-release-$VEP_VERSION/scripts/variant_effect_predictor/

RUN sed -i 's/master/main/g' INSTALL.pl

RUN perl INSTALL.pl -a a

WORKDIR $VEP_DIR

RUN echo "#!/bin/bash" > /vep
RUN echo "export PERL5LIB=$VEP_DIR/loftee:\$PERL5LIB" >> /vep
RUN echo "perl $VEP_DIR/ensembl-tools-release-$VEP_VERSION/scripts/variant_effect_predictor/variant_effect_predictor.pl \"\$@\"" >> /vep
RUN chmod +x /vep

ENV PERL5LIB "$VEP_DIR/loftee:${PERL5LIB}"

COPY vep.py /hail-vep/
